version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: php.Dockerfile
    container_name: php-apache
    ports:
      - 8080:80
    volumes:
      - ./drupal:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./certs/server.crt:/etc/ssl/certs/server.crt
      - ./certs/server.key:/etc/ssl/private/server.key
    depends_on:
      - db
  
  db_phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=drupal_db
      - MARIADB_USER=gabriel
      - MARIADB_PASSWORD=1234
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    
volumes:
  db_data:
